bucket_name = "image-resizer-bucket-stg"
bucket_policy_name = "image-resizer-bucket-policy-stg"
acr_name    = "image-resizer-registry-stg"
user_name   = "image-resizer-user-stg"
task_definition_name = "image-resizer-task-stg"
cluster_name = "image-resizer-cluster-stg"
ecs_role_name = "image-resizer-ecs-role-stg"
aws_region  = "us-east-1"